### ISSUE TITLE
lxml should be added as a dependency

### ISSUE THREAD

**Issue by msmitty12** [ranaroussi/yfinance#227]
In a virtual environment, I installed yfinance. When I tried to import the package, I saw the following error:
```
Traceback (most recent call last):
  File "stock.py", line 5, in <module>
    print(msft.info)
  File "/Users/mksmith/personal/gitprojects/finance/venv/lib/python3.7/site-packages/yfinance/ticker.py", line 138, in info
    return self.get_info()
  File "/Users/mksmith/personal/gitprojects/finance/venv/lib/python3.7/site-packages/yfinance/base.py", line 415, in get_info
    self._get_fundamentals(proxy)
  File "/Users/mksmith/personal/gitprojects/finance/venv/lib/python3.7/site-packages/yfinance/base.py", line 284, in _get_fundamentals
    holders = _pd.read_html(url)
  File "/Users/mksmith/personal/gitprojects/finance/venv/lib/python3.7/site-packages/pandas/io/html.py", line 1100, in read_html
    displayed_only=displayed_only,
  File "/Users/mksmith/personal/gitprojects/finance/venv/lib/python3.7/site-packages/pandas/io/html.py", line 891, in _parse
    parser = _parser_dispatch(flav)
  File "/Users/mksmith/personal/gitprojects/finance/venv/lib/python3.7/site-packages/pandas/io/html.py", line 848, in _parser_dispatch
    raise ImportError("lxml not found, please install it")
ImportError: lxml not found, please install it
```
`lxml` probably needs to be added to this list: https://github.com/ranaroussi/yfinance/blob/master/setup.py#L53

**Comment by Qrishna** [comment]
I second this. I deployed a web app in Heroku using this module and took me a while to figure out why my app was failing and it turns out lxml was missing as a dependency.

**Comment by ElSaico** [comment]
Thirded.

It's an optional dependency for Pandas, but `read_html()` requires it.

**Comment by muroshi** [comment]
Still missing.

**Comment by ApurvShah007** [comment]
Still missing. Somehow even after I installed it, I can not use functions like ticker.cashflow or ticker.earning. 

Get this error: 
ImportError: lxml not found, please install it

**Comment by raphdemtl** [comment]
still the same error even when installing lxml
has been it solved ?

**Comment by yauhen-info** [comment]
I can confirm the issue occurs to me as well. 
Under fresh conda env at MacOs Catalina 10.15.5 (19F101):
```
conda create -n yfinance python=3.8
➜ python                                       
Python 3.8.5 (default, Aug  5 2020, 03:39:04) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import yfinance as yf
>>> info = yf.Ticker("INFO")
>>> info.actions
            Dividends  Stock Splits
Date                               
2016-07-13       0.00           3.0
2020-02-05       0.17           0.0
2020-04-29       0.17           0.0
2020-07-30       0.17           0.0
>>> info.sustainability
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yauhen/miniconda/envs/yfinance/lib/python3.8/site-packages/yfinance/ticker.py", line 190, in sustainability
    return self.get_sustainability()
  File "/Users/yauhen/miniconda/envs/yfinance/lib/python3.8/site-packages/yfinance/base.py", line 422, in get_sustainability
    self._get_fundamentals(proxy)
  File "/Users/yauhen/miniconda/envs/yfinance/lib/python3.8/site-packages/yfinance/base.py", line 284, in _get_fundamentals
    holders = _pd.read_html(url)
  File "/Users/yauhen/miniconda/envs/yfinance/lib/python3.8/site-packages/pandas/util/_decorators.py", line 296, in wrapper
    return func(*args, **kwargs)
  File "/Users/yauhen/miniconda/envs/yfinance/lib/python3.8/site-packages/pandas/io/html.py", line 1086, in read_html
    return _parse(
  File "/Users/yauhen/miniconda/envs/yfinance/lib/python3.8/site-packages/pandas/io/html.py", line 894, in _parse
    parser = _parser_dispatch(flav)
  File "/Users/yauhen/miniconda/envs/yfinance/lib/python3.8/site-packages/pandas/io/html.py", line 851, in _parser_dispatch
    raise ImportError("lxml not found, please install it")
ImportError: lxml not found, please install it
```
After installing lxml

```
➜ pip install lxml                   
Collecting lxml
  Downloading lxml-4.5.2-cp38-cp38-macosx_10_9_x86_64.whl (4.5 MB)
     |████████████████████████████████| 4.5 MB 1.7 MB/s 
Installing collected packages: lxml
Successfully installed lxml-4.5.2
(yfinance) 

```
I was able to load the expected results
```
>>> info.sustainability
                                     Value
2020-8                                    
palmOil                              False
controversialWeapons                 False
gambling                             False
socialScore                          15.92
nuclear                              False
furLeather                           False
alcoholic                            False
gmo                                  False
catholic                             False
socialPercentile                         0
peerCount                                0
governanceScore                       8.14
environmentPercentile                    0
animalTesting                        False
tobacco                              False
totalEsg                              24.1
highestControversy                       1
esgPerformance                    AVG_PERF
coal                                 False
pesticides                           False
adult                                False
percentile                           34.88
peerGroup              Commercial Services
smallArms                            False
environmentScore                      0.05
governancePercentile                     0
militaryContract                     False
```

**Comment by akashkj** [comment]
Just leaving a comment that issue still exists.
```
>>> from yfinance import Ticker
>>> t= Ticker("MSFT")
>>> t.info
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/yfinance/ticker.py", line 138, in info
    return self.get_info()
  File "/usr/local/lib/python3.8/site-packages/yfinance/base.py", line 415, in get_info
    self._get_fundamentals(proxy)
  File "/usr/local/lib/python3.8/site-packages/yfinance/base.py", line 284, in _get_fundamentals
    holders = _pd.read_html(url)
  File "/usr/local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 296, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pandas/io/html.py", line 1086, in read_html
    return _parse(
  File "/usr/local/lib/python3.8/site-packages/pandas/io/html.py", line 894, in _parse
    parser = _parser_dispatch(flav)
  File "/usr/local/lib/python3.8/site-packages/pandas/io/html.py", line 851, in _parser_dispatch
    raise ImportError("lxml not found, please install it")
ImportError: lxml not found, please install it
```
Any reason for not adding it as a dependency?

**Comment by silvavn** [comment]
This has been addressed.
from `requirements.txt`:
`lxml>=4.5.1`
