### ISSUE TITLE
JSONDecodeError base.py

### ISSUE THREAD

**Issue by lm913** [ranaroussi/yfinance#318]
I don't get this error frequently (maybe once every other day) but it seems to stem from something trying to json decode Python's `None` value.

```
Exception in thread Thread-2960:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/Repositories/trading/env/lib/python3.7/site-packages/multitasking/__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "/home/pi/Repositories/trading/env/lib/python3.7/site-packages/yfinance/multi.py", line 167, in _download_one_threaded
    actions, period, interval, prepost, proxy, rounding)
  File "/home/pi/Repositories/trading/env/lib/python3.7/site-packages/yfinance/multi.py", line 182, in _download_one
    rounding=rounding, many=True)
  File "/home/pi/Repositories/trading/env/lib/python3.7/site-packages/yfinance/base.py", line 155, in history
    data = data.json()
  File "/home/pi/Repositories/trading/env/lib/python3.7/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Because of its infrequent nature and because I run a batch every night I can't really pinpoint what causes it. The only line I use for retrieving data through yfinance is:

`stock_data = yf.download(symbol, start_date, end_date, interval='1d')`

I initialize `stock_data` with this line.

**Comment by rodrigobercini** [comment]
Could you provide which symbols are you trying to query?

**Comment by lm913** [comment]
Unfortunately not. I run this screen on >8000 symbols overnight and wasn't logging the symbols with errors at the time. I did put a try/except around the `data = data.json()` line and haven't had any issues since then

**Comment by andrewni4313** [comment]
Hi,

I am having the same issue.

```
Traceback (most recent call last):
  File "C:/Users/andre/OneDrive/Documents/InvestmentPlatform/InvestmentPlatform/venv/test.py", line 50, in <module>
    stock_list.append(ip.Stock(stock, 'trading'))
  File "C:\Users\andre\OneDrive\Documents\InvestmentPlatform\InvestmentPlatform\venv\investment_platform.py", line 42, in __init__
    self.data = yf.Ticker(self.ticker).history(period='max')
  File "C:\Users\andre\OneDrive\Documents\InvestmentPlatform\InvestmentPlatform\venv\lib\site-packages\yfinance\base.py", line 155, in history
    data = data.json()
  File "C:\Users\andre\OneDrive\Documents\InvestmentPlatform\InvestmentPlatform\venv\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Process finished with exit code 1
```

So I added the try/except as @lm913  suggested:

```
try:
    data = data.json()
except:
    pass
```

I'm not sure what to add to the except statement to completely fix this error. Adding the try/except, however, did help me identify which one of the symbols this occurs on (or rather all of them) as `No data found for this date range, symbol may be delisted` occurs instead. The problem is the error occurs on **random stocks** almost **every time** I run my program.

Note: I fall back on investpy instead of yfinance for these cases 

For example, one run:
```
- ^GSPC: No data found for this date range, symbol may be delisted
- CNP: No data found for this date range, symbol may be delisted
yfinance failed falling back on investpy
- GILD: No data found for this date range, symbol may be delisted
yfinance failed falling back on investpy
- HD: No data found for this date range, symbol may be delisted
yfinance failed falling back on investpy
- RCL: No data found for this date range, symbol may be delisted
yfinance failed falling back on investpy
- GDX: No data found for this date range, symbol may be delisted
yfinance failed falling back on investpy`
```

Another run, right after:
```
- ^GSPC: No data found for this date range, symbol may be delisted
- BYND: No data found for this date range, symbol may be delisted
yfinance failed falling back on investpy
- FB: No data found for this date range, symbol may be delisted
yfinance failed falling back on investpy
- GD: No data found for this date range, symbol may be delisted
yfinance failed falling back on investpy
- UBER: No data found for this date range, symbol may be delisted
yfinance failed falling back on investpy

```
The stocks this occurs on is completely random. This issue was also not occurring up until yesterday for me and I have not made any major changes. I tried reinstalling yfinance as well, no help.

Any help would be appreciated, thanks!

**Comment by xBIGGIExDUBSx** [comment]
Having the same issue as well. I'm also downloading a large amount of data (entire S&P 500 constituents). Can confirm that it appears to be completely random. I've tested by putting in stocks manually as well. I don't think anyone else mentioned this, but in my case the download does not complete. It usually gets locked up around the 90% range. In terms of how often this error occurs, that's also completely random.

**Comment by alanzou** [comment]
It seems that yahoo blocks large amount of data download at high speed, I added time.sleep(30) between each download, the error is gone.

**Comment by AntonioHidalgoLanda** [comment]
Hi, consistently with the comments from @alanzou, I have realized that the issue is intermittent, and if you retry the call, it probably returns the right data. I have introduced this wrapper into my code. I think that it could be a good idea to enable retries into the function to get history data.
```

def ticker_history(start, end, interval, yf_ticker):
    for retries in range (0,5):
        try:
            history = yf_ticker.history(start = start,
                                 end = end,
                                 interval = interval)
            return history
        except:
            print ('yfinance JSONDecodeError, retyring: ' + str(retries))
            print ('ticker: ' + yf_ticker.ticker + 'start: ' + str(start) + ';end: ' + str(end) + ';interval: ' + interval)
            time.sleep(5*retries)
            
    return None
```

**Comment by andrewni4313** [comment]
Thanks, the wrapper works like a charm!
This only recently started erroring for me very recently and seems like others too:
#360 #361 #359 
For now, the wrapper is fine for a workaround for me.

**Comment by xBIGGIExDUBSx** [comment]
I built a different workaround in case anyone wants to use yf.download. This method creates a df using a pull of SPY data (I use as a benchmark) and then amends the existing df for each stock that is provided in a lists (tickers). I'm only interested in the close price so I drop all the unnecessary columns before merging the dfs. 

```
data = yf.download("SPY", start="2017-01-01", end= trade_date)
data = data.drop(columns = ['Low','High', 'Open', 'Adj Close', 'Volume'])
data.columns=['SPY']
close_data = data.reset_index()

for x in tickers:
    while True:
        try:
            data = yf.download(x, start="2017-01-01", end=trade_date, threads = False)
            data = data.drop(columns = ['Low','High', 'Open', 'Adj Close', 'Volume'])
            data.columns=[x]
            data = data.reset_index()
            stock_data=data[x]
            close_data = pd.concat([close_data,stock_data], axis=1)
            print(x)
        except Exception as ex:
            print(ex)
            continue
        break
```

**Comment by a-souljah** [comment]
@AntonioHidalgoLanda 
Hi there, can you please provide me with a bit more context on what your wrap does? I honestly started learning python on June 17th, and wrote some bare-bone code to pull stock data using yfinance and all of a sudden I started getting the error yesterday. I noticed that you guys seemed to be getting the same error, and that it works for y'all. I don't quite understand what it's actually doing though. What is ticker_history? yf_ticker? yf.ticker.ticker? Appreciate any help.
Thank you

**Comment by swankyshahir** [comment]
thanks AntonioHidalgoLanda  wrapper works...!!

**Comment by swankyshahir** [comment]
@AntonioHidalgoLanda error still occurs with this wrapper though.

**Comment by Vanigan** [comment]
Hi.
I am calling around 150 scrips in a for loop through
yf.download(sc, period=period, interval=interval)
in between the program hangs. The program doesnt show any error nor it progresses.

The for loop where it gets stuck is given below:

def my_condition(sc, period, interval):
while condition1:
try:
data = yf.download(sc, period=period, interval=interval)

Any help please.

**Comment by Vanigan** [comment]
I tried adding exception.
The problem is it doesnt show any error. the program is getting hang.
The program is getting hang exactly at yf.download()

My code is here

from bs4 import BeautifulSoup
import requests
import pandas as pd
import yfinance as yf
import ta
from datetime import datetime, time, timedelta, date
from time import sleep

scr = ["ADANIENT.NS", "ADANIPORTS.NS", "ADANIPOWER.NS", "AMARAJABAT.NS", "AMBUJACEM.NS", "APOLLOHOSP.NS", "APOLLOTYRE.NS", "ASHOKLEY.NS", "ASIANPAINT.NS","AUROPHARMA.NS", "AXISBANK.NS", .... 150 scrips]

def my_function(sc, period, interval):
sc.replace(',', '-')
while my_condition:
try:
data = yf.download(sc, period=period, interval=interval)
ans, region = ----my logic (including my_condition)---
except Exception as ex:
print(ex)
return ans, region

for x in scr:
now = datetime.now()
print(x, now)
an, re = my_function(x, '25d', '60m')

The screenshots of my output panels is here. Check out the time in the screenshots, it stops at some random scrip and neither shows any error nor progress. Once it gets hang, the program is required to be manually terminated.

if I print('Helo World') just before yf.download(), the terminal shows the Helo World and the program is hung at some random scrip without showing the
[100%**] 1 of 1 completed
message.

so the problem is not with my while loop.

![hang1](https://user-images.githubusercontent.com/67513689/85940170-762a1d00-b938-11ea-89da-6b746cb41161.PNG)
![hang2](https://user-images.githubusercontent.com/67513689/85940171-76c2b380-b938-11ea-941f-2ed4b2f89aa8.PNG)
![hang3](https://user-images.githubusercontent.com/67513689/85940173-775b4a00-b938-11ea-8a32-7bc1ef3f2a7d.PNG)

**Comment by swankyshahir** [comment]
> Unfortunately not. I run this screen on >8000 symbols overnight and wasn't logging the symbols with errors at the time. I did put a try/except around the `data = data.json()` line and haven't had any issues since then

could you post a code snippet of how you use data.json() to overcome this problem..

**Comment by Vanigan** [comment]
Here is a code which is getting stuck at some random scrip

please try it

`import yfinance as yf
from datetime import datetime

scr = ['^NSEI', '^NSEBANK', 'ADANIENT.NS', 'ADANIPORTS.NS', 'ADANIPOWER.NS', 'AMARAJABAT.NS', 'AMBUJACEM.NS', 'APOLLOHOSP.NS', 'APOLLOTYRE.NS', 'ASHOKLEY.NS', 'ASIANPAINT.NS', 'AUROPHARMA.NS', 'AXISBANK.NS', 'BAJAJ-AUTO.NS', 'BAJAJFINSV.NS', 'BAJFINANCE.NS', 'BALKRISIND.NS', 'BANDHANBNK.NS', 'BANKBARODA.NS', 'BATAINDIA.NS', 'BEL.NS', 'BERGEPAINT.NS', 'BHARATFORG.NS', 'BHARTIARTL.NS', 'BHEL.NS', 'BIOCON.NS', 'BOSCHLTD.NS', 'BPCL.NS', 'BRITANNIA.NS', 'CADILAHC.NS', 'CANBK.NS', 'CENTURYTEX.NS', 'CHOLAFIN.NS', 'CIPLA.NS', 'COALINDIA.NS', 'COLPAL.NS', 'CONCOR.NS', 'CUMMINSIND.NS', 'DABUR.NS', 'DIVISLAB.NS', 'DLF.NS', 'DRREDDY.NS', 'EICHERMOT.NS', 'EQUITAS.NS', 'ESCORTS.NS', 'EXIDEIND.NS', 'FEDERALBNK.NS', 'GAIL.NS', 'GLENMARK.NS', 'GMRINFRA.NS', 'GODREJCP.NS', 'GODREJPROP.NS', 'GRASIM.NS', 'HAVELLS.NS', 'HCLTECH.NS', 'HDFC.NS', 'HDFCBANK.NS', 'HDFCLIFE.NS', 'HEROMOTOCO.NS', 'HINDALCO.NS', 'HINDPETRO.NS', 'HINDUNILVR.NS', 'IBULHSGFIN.NS', 'ICICIBANK.NS', 'ICICIPRULI.NS', 'IDEA.NS', 'IDFCFIRSTB.NS', 'IGL.NS', 'INDIGO.NS', 'INDUSINDBK.NS', 'INFRATEL.NS', 'INFY.NS', 'IOC.NS', 'ITC.NS', 'JINDALSTEL.NS', 'JSWSTEEL.NS', 'JUBLFOOD.NS', 'JUSTDIAL.NS', 'KOTAKBANK.NS', 'L&TFH.NS', 'LICHSGFIN.NS', 'LT.NS', 'LUPIN.NS', 'M&M.NS', 'M&MFIN.NS', 'MANAPPURAM.NS', 'MARICO.NS', 'MARUTI.NS', 'MCDOWELL-N.NS', 'MFSL.NS', 'MGL.NS', 'MINDTREE.NS', 'MOTHERSUMI.NS', 'MRF.NS', 'MUTHOOTFIN.NS', 'NATIONALUM.NS', 'NAUKRI.NS', 'NCC.NS', 'NESTLEIND.NS', 'NIITTECH.NS', 'NMDC.NS', 'NTPC.NS', 'ONGC.NS', 'PAGEIND.NS', 'PEL.NS', 'PETRONET.NS', 'PFC.NS', 'PIDILITIND.NS', 'PNB.NS', 'POWERGRID.NS', 'PVR.NS', 'RAMCOCEM.NS', 'RBLBANK.NS', 'RECLTD.NS', 'RELIANCE.NS', 'SAIL.NS', 'SBILIFE.NS', 'SBIN.NS', 'SHREECEM.NS', 'SIEMENS.NS', 'SRF.NS', 'SRTRANSFIN.NS', 'SUNPHARMA.NS', 'SUNTV.NS', 'TATACHEM.NS', 'TATACONSUM.NS', 'TATAMOTORS.NS', 'TATAPOWER.NS', 'TATASTEEL.NS', 'TCS.NS', 'TECHM.NS', 'TITAN.NS', 'TORNTPHARM.NS', 'TORNTPOWER.NS', 'TVSMOTOR.NS', 'UBL.NS', 'UJJIVAN.NS', 'ULTRACEMCO.NS', 'UPL.NS', 'VEDL.NS', 'VOLTAS.NS', 'WIPRO.NS', 'ZEEL.NS']

def my_condition(sc, period, interval):
    sc.replace(',', '-')
    try:
        data = yf.download(sc, period=period, interval=interval)
    except Exception as ex:
        print(ex)

while True:
    for s in scr:
        now = datetime.now()
        print(s, now)
        my_condition(s, '25d', '60m')`

**Comment by alanzou** [comment]
pandas_datareader is not working randomly, it must be related to yahoo service.

**Comment by Vanigan** [comment]
I tried running this code
It hangs at some random scrip

Is there any restriction from yahoo??

```
import yfinance as yf
from datetime import datetime

scr = ['^NSEI', '^NSEBANK', 'ADANIENT.NS', 'ADANIPORTS.NS', 'ADANIPOWER.NS', 'AMARAJABAT.NS', 'AMBUJACEM.NS', 'APOLLOHOSP.NS', 'APOLLOTYRE.NS', 'ASHOKLEY.NS', 'ASIANPAINT.NS', 'AUROPHARMA.NS', 'AXISBANK.NS', 'BAJAJ-AUTO.NS', 'BAJAJFINSV.NS', 'BAJFINANCE.NS', 'BALKRISIND.NS', 'BANDHANBNK.NS', 'BANKBARODA.NS', 'BATAINDIA.NS', 'BEL.NS', 'BERGEPAINT.NS', 'BHARATFORG.NS', 'BHARTIARTL.NS', 'BHEL.NS', 'BIOCON.NS', 'BOSCHLTD.NS', 'BPCL.NS', 'BRITANNIA.NS', 'CADILAHC.NS', 'CANBK.NS', 'CENTURYTEX.NS', 'CHOLAFIN.NS', 'CIPLA.NS', 'COALINDIA.NS', 'COLPAL.NS', 'CONCOR.NS', 'CUMMINSIND.NS', 'DABUR.NS', 'DIVISLAB.NS', 'DLF.NS', 'DRREDDY.NS', 'EICHERMOT.NS', 'EQUITAS.NS', 'ESCORTS.NS', 'EXIDEIND.NS', 'FEDERALBNK.NS', 'GAIL.NS', 'GLENMARK.NS', 'GMRINFRA.NS', 'GODREJCP.NS', 'GODREJPROP.NS', 'GRASIM.NS', 'HAVELLS.NS', 'HCLTECH.NS', 'HDFC.NS', 'HDFCBANK.NS', 'HDFCLIFE.NS', 'HEROMOTOCO.NS', 'HINDALCO.NS', 'HINDPETRO.NS', 'HINDUNILVR.NS', 'IBULHSGFIN.NS', 'ICICIBANK.NS', 'ICICIPRULI.NS', 'IDEA.NS', 'IDFCFIRSTB.NS', 'IGL.NS', 'INDIGO.NS', 'INDUSINDBK.NS', 'INFRATEL.NS', 'INFY.NS', 'IOC.NS', 'ITC.NS', 'JINDALSTEL.NS', 'JSWSTEEL.NS', 'JUBLFOOD.NS', 'JUSTDIAL.NS', 'KOTAKBANK.NS', 'L&TFH.NS', 'LICHSGFIN.NS', 'LT.NS', 'LUPIN.NS', 'M&M.NS', 'M&MFIN.NS', 'MANAPPURAM.NS', 'MARICO.NS', 'MARUTI.NS', 'MCDOWELL-N.NS', 'MFSL.NS', 'MGL.NS', 'MINDTREE.NS', 'MOTHERSUMI.NS', 'MRF.NS', 'MUTHOOTFIN.NS', 'NATIONALUM.NS', 'NAUKRI.NS', 'NCC.NS', 'NESTLEIND.NS', 'NIITTECH.NS', 'NMDC.NS', 'NTPC.NS', 'ONGC.NS', 'PAGEIND.NS', 'PEL.NS', 'PETRONET.NS', 'PFC.NS', 'PIDILITIND.NS', 'PNB.NS', 'POWERGRID.NS', 'PVR.NS', 'RAMCOCEM.NS', 'RBLBANK.NS', 'RECLTD.NS', 'RELIANCE.NS', 'SAIL.NS', 'SBILIFE.NS', 'SBIN.NS', 'SHREECEM.NS', 'SIEMENS.NS', 'SRF.NS', 'SRTRANSFIN.NS', 'SUNPHARMA.NS', 'SUNTV.NS', 'TATACHEM.NS', 'TATACONSUM.NS', 'TATAMOTORS.NS', 'TATAPOWER.NS', 'TATASTEEL.NS', 'TCS.NS', 'TECHM.NS', 'TITAN.NS', 'TORNTPHARM.NS', 'TORNTPOWER.NS', 'TVSMOTOR.NS', 'UBL.NS', 'UJJIVAN.NS', 'ULTRACEMCO.NS', 'UPL.NS', 'VEDL.NS', 'VOLTAS.NS', 'WIPRO.NS', 'ZEEL.NS']

def my_condition(sc, period, interval):
    sc.replace(',', '-')
    try:
        data = yf.download(sc, period=period, interval=interval)
    except Exception as ex:
        print(ex)

while True:
    for s in scr:
        now = datetime.now()
        print(s, now)
        my_condition(s, '25d', '60m')

**Comment by seeohsee** [comment]
This just started becoming an issue for me 2 days ago, and now it happens every time I try to pull data (in a loop). I can get anywhere between 7-14 successful fetches, and then I get the JSONDecode error:

`...
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

It is seemingly random which tickers it fails on, as all my tickers are indeed valid.

I've also tried adding a `time.sleep(10)`, but this doesn't prevent the issue. I have ~1000 tickers I'm looking to update, and now can not get past 14-15 tickers. Error is 100% reproducible.

**Comment by igor555** [comment]
@AntonioHidalgoLanda 
Great wrapper thank you! 
Any idea how to make it faster? I have 80+ tickers and the sleep is taking so long

**Comment by xBIGGIExDUBSx** [comment]
> This just started becoming an issue for me 2 days ago, and now it happens every time I try to pull data (in a loop). I can get anywhere between 7-14 successful fetches, and then I get the JSONDecode error:
> 
> `... File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`
> 
> It is seemingly random which tickers it fails on, as all my tickers are indeed valid.
> 
> I've also tried adding a `time.sleep(10)`, but this doesn't prevent the issue. I have ~1000 tickers I'm looking to update, and now can not get past 14-15 tickers. Error is 100% reproducible.

FYI the wrapper I built (above) retries the download until it is successful, without the need for sleep. I still see the JSON errors occurring but it fixes itself by retrying. Antonio's code does not have the "while true" clause that allows for retries.

**Comment by igor555** [comment]
@xBIGGIExDUBSx 

In your code, the continue will just retry the same ticker again, right?  and the break will move to the next ticker? 

So I can do something like this?

    for ticker in TICKER_DICT:
        while True:
            try:        
                yf_data = yf.Ticker(TICKER_DICT[ticker])
                daily_ticker_hist = yf_data.history(period="max", interval="1d")
                weekly_ticker_hist = yf_data.history(period="max", interval="1wk")
            except:
                print ('yfinance JSONDecodeError WEEKLY, retyring: ' + str(retries))
                print ('ticker: ' + TICKER_DICT[ticker])
                print()
                continue
            break

    rest of the code
    more code

**Comment by xBIGGIExDUBSx** [comment]
@igor555 

That's correct. Obviously your case is different because you are using yf.ticker rather than yf.download. However, the methodology should be able to work for your case after tinkering with it a bit. Mine has worked flawlessly since I implemented the fix. It's also doesn't require time.sleep, which I wanted to avoid using because A )the added time was very annoying and B) it would still produce errors. 

If you need all HLOC, you may have some difficulty manipulating the data for each pull. For example, I drop every other column besides Close because the way the dataframes merges caused some difficulty otherwise. This is a relatively easy fix though, as you can just create multiple data frames (one for each data type) and then merge them together after the loop has completed. 

Also, go Ravens!

**Comment by igor555** [comment]
@xBIGGIExDUBSx 

This was my final code thanks to you and the others. It seems to work without the sleep module.

    for ticker in TICKER_DICT:
        while True:
            try:        
                yf_data = yf.Ticker(TICKER_DICT[ticker])
                daily_ticker_hist = yf_data.history(period="max", interval="1d")
            except:
                print ('yfinance JSONDecodeError DAILY, retyring')
                print ('ticker: ' + TICKER_DICT[ticker])
                continue
            break  
        
        time_period_exc_na = daily_ticker_hist.dropna()
        copied_data = time_period_exc_na.copy(deep=True)

**Comment by viniciuscover** [comment]
Even using try/except I've got the same error. When I took a look at multi.py where download method relies I found the option to without using threads, so I started using download method with (threads=False) argument inside a try/except. Now it's working fine for me.

**Comment by seeohsee** [comment]
@vcover86 Thanks for this. Your method does seem to work for longer than it would have without threads=False, but this does not fix the problem for me. When trying to pull ~1000 tickers with `df = pdr.get_data_yahoo(ticker,start,end)` I can get to about 50 tickers now (could only get to about 10 before), and then the JSONDecodeError arises.

**Comment by xBIGGIExDUBSx** [comment]
@vcover86 
@seeohsee 

You need to include a clause in the wrapper that allows for retries. The reason you are still going to get errors is because this error occurs **randomly.** I was able to reproduce this error on the first query, meaning that it's not dependent on the number of tickers you are trying to download data for. This is also why time.sleep does not work when pulling a large amount of tickers. You need to produce a wrapper that has "while True" in it and forces the download to retry on downloads that produce an error when threads = False. You can refer to my original comment above, in which I shared the entire code and explained my methodology when using yf.download. @igor555 also successfully replicated the fix using yf.ticker. I'm sure you can create some sort of a fix using the pdr methodology.

**Comment by AntonioHidalgoLanda** [comment]
> 
> 
> @AntonioHidalgoLanda
> Hi there, can you please provide me with a bit more context on what your wrap does? I honestly started learning python on June 17th, and wrote some bare-bone code to pull stock data using yfinance and all of a sudden I started getting the error yesterday. I noticed that you guys seemed to be getting the same error, and that it works for y'all. I don't quite understand what it's actually doing though. What is ticker_history? yf_ticker? yf.ticker.ticker? Appreciate any help.
> Thank you

Hi @a-souljah, ticker_history is a wrapper function, so you would be using ticker_history() instead of ticker.history(). yf_ticker is a variable of the class Ticker, and yf_ticker.ticker is a field represents the ticker in a string format and capitalized.

**Comment by AntonioHidalgoLanda** [comment]
> 
> 
> @AntonioHidalgoLanda error still occurs with this wrapper though.

Hi @swankyshahir,
Are you getting the same error or a different message? You may want to tune the sleeping time and the retries. In my case, I get most of the time success with less than 2 retries. My expectation is that depending the network and the load of the network you may need either more waiting time or more re-tries.

**Comment by AntonioHidalgoLanda** [comment]
> 
> 
> @AntonioHidalgoLanda
> Great wrapper thank you!
> Any idea how to make it faster? I have 80+ tickers and the sleep is taking so long

Hi @igor555, I made the wait time progressively longer. In my case, It didn't need too many retries. I can suggestion to decrease the waiting time or making it constant.
`
time.sleep(2) 
`

**Comment by seeohsee** [comment]
> @vcover86
> @seeohsee
> 
> You need to include a clause in the wrapper that allows for retries. The reason you are still going to get errors is because this error occurs **randomly.** I was able to reproduce this error on the first query, meaning that it's not dependent on the number of tickers you are trying to download data for. This is also why time.sleep does not work when pulling a large amount of tickers. You need to produce a wrapper that has "while True" in it and forces the download to retry on downloads that produce an error when threads = False. You can refer to my original comment above, in which I shared the entire code and explained my methodology when using yf.download. @igor555 also successfully replicated the fix using yf.ticker. I'm sure you can create some sort of a fix using the pdr methodology.

@xBIGGIExDUBSx I appreciate your reply. I will try implementing the while wrapper at some point today. While I'm confident that your solution will fix the issue insomuch as I'll be able to eventually pull all the data that I need, what would be great is if we could get to the root of the issue. I was hoping that there was an error in the threads method of multi.py which might be causing the issue, but that doesn't seem to be the case.

Do we think this is an issue on Yahoo's end?

**Comment by andrewni4313** [comment]
I have a hunch it is an issue/change on Yahoo's end since it occurred so recently for so many people, unless there were some recent changes to yfinance I'm not aware of. (a new limit from yahoo perhaps?)
#363 #361 #360 #359

**Comment by seeohsee** [comment]
The solution offered by @xBIGGIExDUBSx https://github.com/ranaroussi/yfinance/issues/318#issuecomment-650630068 worked for me. Until it's fully fixed, this seems to be the best workaround.

I've wrapped my downloads within a loop of ~1000 tickers and it never needs more than one retry per failed ticker. I also do not have a `time.sleep()` call enabled, so I don't think Yahoo is throttling how much data is pulled in a given time window.

**Comment by xBIGGIExDUBSx** [comment]
FYI I've been investigating this and made some interesting observations. Here is an error code for a download. The DL fails the first attempt and is then successful in the retry. 

`1 Failed download:
- CSCO: No data found, symbol may be delisted
CSCO
[*********************100%***********************]  1 of 1 completed`

I knew for a fact that Cisco was a listed firm and should have data available. When I searched for CSCO on Yahoo, no results appeared, which makes no sense. It redirected me to a page that said "Symbols similar to 'csco.'" The same error occurred when I followed a link to the CSCO Yahoo finance page directly from a google search. I used a different computer in my house and the same error occurred. I tested 15 errors and this was the case for **all** of them. 

Here is where it's interesting: the Yahoo finance website issue only occurred while I was in the process of downloading the data. A few seconds after the download completed, I was able to view the data on the website. 

If anyone has the time or inclination, can you see if you can replicate this? I'm inclined to conclude that this has something to do with Yahoo limiting data downloads.

**Comment by swankyshahir** [comment]
> @seeohsee
> 
> > This just started becoming an issue for me 2 days ago, and now it happens every time I try to pull data (in a loop). I can get anywhere between 7-14 successful fetches, and then I get the JSONDecode error:
> > `... File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`
> > It is seemingly random which tickers it fails on, as all my tickers are indeed valid.
> > I've also tried adding a `time.sleep(10)`, but this doesn't prevent the issue. I have ~1000 tickers I'm looking to update, and now can not get past 14-15 tickers. Error is 100% reproducible.
> 
> FYI the wrapper I built (above) retries the download until it is successful, without the need for sleep. I still see the JSON errors occurring but it fixes itself by retrying. Antonio's code does not have the "while true" clause that allows for retries. His method is slightly different.

his is the best work around at the moment. thanks a ton.

**Comment by lm913** [comment]
> @igor555
> 
> That's correct. Obviously your case is different because you are using yf.ticker rather than yf.download. However, the methodology should be able to work for your case after tinkering with it a bit. Mine has worked flawlessly since I implemented the fix. It's also doesn't require time.sleep, which I wanted to avoid using because A )the added time was very annoying and B) it would still produce errors.
> 
> If you need all HLOC, you may have some difficulty manipulating the data for each pull. For example, I drop every other column besides Close because the way the dataframes merges caused some difficulty otherwise. This is a relatively easy fix though, as you can just create multiple data frames (one for each data type) and then merge them together after the loop has completed.
> 
> Also, go Ravens!
> 
> Edit: Looking at your code, i believe each try may overwrite the existing data. In my methodology, I create an initial dataframe **outside** of the loop, then amend that dataframe with the new data every time the loop is ran.

Thanks for the wrapper! Also are you from Baltimore? I lived there for a few years in Mount Vernon

**Comment by 100330706** [comment]
Hi guys. It might be due to the 2000 requests/hour per IP of the Yahoo Finance API: https://stackoverflow.com/questions/9346582/what-is-the-query-limit-on-yahoos-finance-api

**Comment by NeelChotai** [comment]
> Hi guys. It might be due to the 2000 requests/hour per IP of the Yahoo Finance API: https://stackoverflow.com/questions/9346582/what-is-the-query-limit-on-yahoos-finance-api

There is no Yahoo Finance API anymore.

**Comment by zapparo** [comment]
There might be a problem with the response, I had a wrong id containing a '/' instead of '-' AGM/A vs AGM-A and the decoder was crapping out on me, I fixed it by actually using the correct symbol but I also added a 404 check in the data.text to catch stuff like that
``` 
       if "HTTP 404 Not Found" in data.text:
            err_msg = "HTTP 404 at " + url
            shared._DFS[self.ticker] = utils.empty_df()
            shared._ERRORS[self.ticker] = err_msg
            if "many" not in kwargs and debug_mode:
                print('- %s: %s' % (self.ticker, err_msg))
            return shared._DFS[self.ticker]                                                     
    
        data = data.json()    
```

**Comment by hansiniupadhyay** [comment]
Replace the code in base.py in the package by the below. This should fix the problem.

        # Getting data from json
        url = "{}/v8/finance/chart/{}".format(self._base_url, self.ticker)
        data = _requests.get(url=url, params=params, proxies=proxy)
        # if "Will be right back" in data.text:
        qqq=0
        while "Will be right back" in data.text and qqq<10:
            # raise RuntimeError("*** YAHOO! FINANCE IS CURRENTLY DOWN! ***\n"
            #                    "Our engineers are working quickly to resolve "
            #                    "the issue. Thank you for your patience.")
            _time.sleep(2)
            qqq=qqq+1
            url = "{}/v8/finance/chart/{}".format(self._base_url, self.ticker)
            data = _requests.get(url=url, params=params, proxies=proxy)
        data = data.json()

**Comment by hansiniupadhyay** [comment]
Replace the code in base.py by below:

   # Getting data from json
        url = "{}/v8/finance/chart/{}".format(self._base_url, self.ticker)
        data = _requests.get(url=url, params=params, proxies=proxy)
        # if "Will be right back" in data.text:
        qqq=0
        while "Will be right back" in data.text and qqq<3:
            # raise RuntimeError("*** YAHOO! FINANCE IS CURRENTLY DOWN! ***\n"
            #                    "Our engineers are working quickly to resolve "
            #                    "the issue. Thank you for your patience.")
            _time.sleep(2)
            qqq=qqq+1
            data = _requests.get(url=url, params=params, proxies=proxy)
            if "Will be right back" not in data.text:
                break
        if "Will be right back" in data.text:
            raise RuntimeError("*** YAHOO! FINANCE IS CURRENTLY DOWN! ***\n"
                                "Our engineers are working quickly to resolve "
                                "the issue. Thank you for your patience.")
        data = data.json()

**Comment by rcd71** [comment]
Hola, a mi me ha funcionado simplemente sustituyendo el carácter "/" por "-", he descargado mas de 3000 tickers varias veces en en el mismo día:

datosAnalizar["Symbol"] = datosAnalizar["Symbol"].str.replace("/","-")
datosDescargados = pdr.get_data_yahoo(datosAnalizar["Symbol"].values.tolist(), data_source='yahoo',start=start, end=end, interval="1wk")

Saludos

**Comment by digitaldd** [comment]
I met the same problem. After several assumes without results, i downgraded version of library and it works without problems.

**Comment by pedropcadavid** [comment]
> 
> 
> I built a different workaround in case anyone wants to use yf.download. This method creates a df using a pull of SPY data (I use as a benchmark) and then amends the existing df for each stock that is provided in a lists (tickers). I'm only interested in the close price so I drop all the unnecessary columns before merging the dfs.
> 
> ```
> data = yf.download("SPY", start="2017-01-01", end= trade_date)
> data = data.drop(columns = ['Low','High', 'Open', 'Adj Close', 'Volume'])
> data.columns=['SPY']
> close_data = data.reset_index()
> 
> for x in tickers:
>     while True:
>         try:
>             data = yf.download(x, start="2017-01-01", end=trade_date, threads = False)
>             data = data.drop(columns = ['Low','High', 'Open', 'Adj Close', 'Volume'])
>             data.columns=[x]
>             data = data.reset_index()
>             stock_data=data[x]
>             close_data = pd.concat([close_data,stock_data], axis=1)
>             print(x)
>         except Exception as ex:
>             print(ex)
>             continue
>         break
> ```

Hi @xBIGGIExDUBSx ! I tried your method and also the one proposed by @AntonioHidalgoLanda. However, I still get the same error.  I've heard your IP can get banned but I'm actually using a VPN... nor sure what could be triggering the error.

For reference, I have Anaconda3 for my JP and this is my error:

raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Any thoughts are appreciated!

**Comment by fmellomascarenhas** [comment]
I was trying to use yfinance to download 7000+ tickers. What I realized is that if I reduce it to 2000, no errors are generated. So maybe the error is raised when the number of tickers > 2000.

**Comment by pedropcadavid** [comment]
> I met the same problem. After several assumes without results, i downgraded version of library and it works without problems.

Hey, how do you downgrade it? Thanks!

**Comment by digitaldd** [comment]
> > I met the same problem. After several assumes without results, i downgraded version of library and it works without problems.
> 
> Hey, how do you downgrade it? Thanks!

Hi, I use PyCharm, so this is a way how to do it in it
![Снимок экрана 2021-07-18 в 7 22 23](https://user-images.githubusercontent.com/31233201/126055770-76657711-2d08-48cf-8f67-a20133357dc7.png)

**Comment by pedropcadavid** [comment]
> > > I met the same problem. After several assumes without results, i downgraded version of library and it works without problems.
> > 
> > 
> > Hey, how do you downgrade it? Thanks!
> 
> Hi, I use PyCharm, so this is a way how to do it in it
> ![Снимок экрана 2021-07-18 в 7 22 23](https://user-images.githubusercontent.com/31233201/126055770-76657711-2d08-48cf-8f67-a20133357dc7.png)

Unfortunately my version is 0.1.54 (looks like always has been)  so doubt that the issue is related to the version. Thanks though.

**Comment by sawantsan1986** [comment]
I am facing problem...any solution on this

**Comment by seanling** [comment]
which version of python are you guys using when got the issue? I had the same issue when using python 3.7.7. But not at all on another mac with python 3.7.1. After I tried upgrade the python 3.7.7 to 3.9, it seems OK now

**Comment by pedropcadavid** [comment]
@seanling the issue was fixed with the new python. What a journy to set it up properly with anaconda on my JP notebook!

Here's a good reference for anyone having issues syncing their python to JP. Chances are you didn't install it properly through anaconda (I didn't at first): https://towardsdatascience.com/how-to-set-up-anaconda-and-jupyter-notebook-the-right-way-de3b7623ea4a

Thanks!

**Comment by ripperaim** [comment]
i am using python 3.9.6 still i am facing the error!
updating version didn't help

**Comment by pedropcadavid** [comment]
> i am using python 3.9.6 still i am facing the error!
> updating version didn't help

Did you activate the updated environment on anaconda first? Check which version jupyter is actually running
