### ISSUE TITLE
Proxy use

### ISSUE THREAD

**Issue by nono-london** [ranaroussi/yfinance#66]
Hi,
great work around the api and it is working well.
One think i was thinking to add would be use of proxies via request/session.
Best

**Comment by ranaroussi** [comment]
done! just specify your https proxy using:

``` python
msft = yf.Ticker("MSFT")
msft.history(period="max", proxy="https://10.10.1.10:1080")
```

or via:
``` python
df = ys.download("MSFT", period="max", proxy="https://10.10.1.10:1080")
```

**Comment by nono-london** [comment]
Hi,
Thanks for the update, but it seems that there is an issue due to the renaming..
I can' install it anymore, nor update...

Collecting fix-yahoo-finance
  Using cached https://files.pythonhosted.org/packages/a5/f3/aba3b563452faaea71b4161754991e3143751ec9141d83c4bce05992332a/fix-yahoo-finance-0.1.37.tar.gz

    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\%%\AppData\Local\Temp\pycharm-packaging\fix-yahoo-finance\setup.py", line 19, in <module>
        from fix_yahoo_finance import __version__
      File "C:\Users\%%\AppData\Local\Temp\pycharm-packaging\fix-yahoo-finance\fix_yahoo_finance\__init__.py", line 22, in <module>
        import yfinance
    ModuleNotFoundError: No module named 'yfinance'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\%%%\AppData\Local\Temp\pycharm-packaging\fix-yahoo-finance\

**Comment by ranaroussi** [comment]
Hi

Just use:

```
pip install yfinance
```

And then use:

```
import yfinance as yf

# do stuff here
...
```

On 26 May 2019, at 19:13, nono-london <notifications@github.com> wrote:

Hi,
Thanks for the update, but it seems that there is an issue due to the
renaming..
I can' install it anymore, nor update...

Collecting fix-yahoo-finance
Using cached
https://files.pythonhosted.org/packages/a5/f3/aba3b563452faaea71b4161754991e3143751ec9141d83c4bce05992332a/fix-yahoo-finance-0.1.37.tar.gz

ERROR: Complete output from command python setup.py egg_info:
ERROR: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\%%\AppData\Local\Temp\pycharm-packaging\fix-yahoo-finance\setup.py",
line 19, in <module>
    from fix_yahoo_finance import __version__
  File "C:\Users\%%\AppData\Local\Temp\pycharm-packaging\fix-yahoo-finance\fix_yahoo_finance\__init__.py",
line 22, in <module>
    import yfinance
ModuleNotFoundError: No module named 'yfinance'
----------------------------------------

ERROR: Command "python setup.py egg_info" failed with error code 1 in
C:\Users%%%\AppData\Local\Temp\pycharm-packaging\fix-yahoo-finance\

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/ranaroussi/yfinance/issues/66?email_source=notifications&email_token=AAJBNMVKWKPZR5KIDDRP6STPXKZJDA5CNFSM4HPVINQKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWIIZ7I#issuecomment-496012541>,
or mute the thread

**Comment by nono-london** [comment]
Hi,
Not sure how to do this in pucharm. Installing is usually done via the ide
not pip.
As well your peogram still shows as fix-yahoo in it. Maybe they will update
the repository later.
Thanks

**Comment by nono-london** [comment]
hi,
do you think you can pic up as well the company financial's?
for instance:
https://finance.yahoo.com/quote/JMIA/financials?p=JMIA
best

**Comment by ranaroussi** [comment]
done! look at the updated readme

**Comment by zhenwenc** [comment]
@ranaroussi Hi, `proxy` only works if `threads` sets to `true`, is this expected? Thanks!
