### ISSUE TITLE
yf.download hangs on last item if downloading more than 79 tickers

### ISSUE THREAD

**Issue by stanlee1986** [ranaroussi/yfinance#70]
I'm calling yf.download(tickers, start="2019-01-01", end="2019-05-29", auto_adjust=True, group_by="ticker")

I've tried this with tickers as a space separated string or a list, aa=F, gb=columns, no start or end, different lists of tickers, threads=False . Same result with anaconda 3.7.1 and collaboratory 3.6.7.

**Comment by stanlee1986** [comment]
Ok, I tried putting yf.download() into a for loop and staying below 79 tickers per call:

```
ticks = dfs.loc[:,'symbol'].to_list()[:200]
df = []
for i in range((len(ticks) // 75) + 1):
  time.sleep(1)
  ticker = ticks[-75:]
  ticks = ticks[:-75]
  df.append(download(ticker, start="2019-05-20", end="2019-05-29", auto_adjust=True, group_by="ticker", threads=False))
```
This hung on the second list of 75 tickers (149/200 overall). 

Next I pasted the source into a jupyter notebook and tried inserting _time.sleep(1) into the for loops at line 460 and 474. By doing this I discovered that the code was only using the multi-threaded version (line 460 `isinstance(threads, int)` evaluates to true if `threads = False` because bool is considered int for its purposes (False is 0 and True is 1 - and both evaluate as int and bool for isinstance(), not what I expected ). Recommend changing 460 to `if threads > 1:` to enable single threading with threads = False or threads = 1, while preserving multithreading for threads = True and threads = 2 or more.

Once I enabled single threading with the change to 460, the problem went away in both the looped approach and single batch without any need to slow things down. Would love to know if anyone can reproduce the problem with the threaded version before I go any further.

**Comment by ranaroussi** [comment]
Fixed. Please update yfinance and report back please :)

**Comment by stanlee1986** [comment]
Confirmed works with both threading and sequential. Obviously I should have checked for duplicate tickers in the lists I used to test. Out of curiosity, how did you know this was the issue?

Thanks!

**Comment by ranaroussi** [comment]
I have no good answer to that... Just a hunch  :)

**Comment by hansiniupadhyay** [comment]
I am still facing this issue. The last few symbols does not get downloaded and the download is stuck with no error message. 
Call:
price=yf.download(sym_list,startdate,enddate)

sym_list is a list of 8318 syms

![yfinance stuck](https://user-images.githubusercontent.com/79159854/108094244-9ab04200-704c-11eb-8995-49eaeed4d0c7.PNG)
