### ISSUE TITLE
JSONDecodeError: Expecting value: line 1 column 1 (char 0) al intentar descargar datos de Yahoo Finance

### ISSUE THREAD

**Issue by akitxu** [ranaroussi/yfinance#783]
I have python 3.8.10 and yfinance 0.1.63 installed. I try to import quotes of a value and it returns the error

`JSONDecodeError: Expecting value: line 1 column 1 (char 0) when trying to download data from Yahoo Finance`

How can i solve this problem. I will appreciate help

**Comment by DivyanshP2020** [comment]
I am facing the same error right now.

**Comment by brianhaines** [comment]
I am also facing this issue.

**Comment by brianhaines** [comment]
Resolved after updating. Run this:
pip install yfinance --upgrade --no-cache-dir

**Comment by bowling-knight** [comment]
Great tip @brianhaines, thanks a lot for sharing!

**Comment by guccipepito** [comment]
mvp

**Comment by sanjkm** [comment]
Thanks @brianhaines !

**Comment by hansiniupadhyay** [comment]
Still getting this error:

Exception in thread Thread-212:
Traceback (most recent call last):
  File "C:\Users\aashi\anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\aashi\anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\aashi\anaconda3\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Users\aashi\anaconda3\lib\site-packages\yfinance\multi.py", line 169, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Users\aashi\anaconda3\lib\site-packages\yfinance\multi.py", line 184, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Users\aashi\anaconda3\lib\site-packages\yfinance\base.py", line 162, in history
    data = data.json()
  File "C:\Users\aashi\anaconda3\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\aashi\anaconda3\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\aashi\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\aashi\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)



Any help is appreciated ....

**Comment by akitxu** [comment]
I recommend seeing this link
`https://es.stackoverflow.com/questions/469043/ya-no-es-posible-acceder-a-yahoo-finanzas`

**Comment by vbhalla** [comment]
I tried pip install yfinance --upgrade --no-cache-dir, but still get the same error.  Also uninstall and reinstalled.   Anyone find any other solutions?

**Comment by parkheedo** [comment]
I am still having the JSON error after the upgrade.  Please help!

**Comment by super6liu** [comment]
Adding `requests_cache` session cache worked for me.

**Comment by byteatwork** [comment]
Besides upgrade to the latest version of yfinance. You can also consider upgrade library requests to the latest where there is a fix on this particular error message [https://github.com/psf/requests/pull/5856]

**Comment by milkywade** [comment]
still having JSON error after updating to .63

https://github.com/ranaroussi/yfinance/issues/764#issuecomment-893678309

**Comment by FlynnMa** [comment]
I got this error on 0.1.64

**Comment by steveberdy** [comment]
> Besides upgrade to the latest version of yfinance. You can also consider upgrade library requests to the latest where there is a fix on this particular error message [https://github.com/[psf/requests/pull/5856](https://github.com/psf/requests/pull/5856)]

That code was recently released in the Requests [2.27.0](https://github.com/psf/requests/releases/tag/v2.27.0) release. The latest version is [2.27.1](https://github.com/psf/requests/releases/tag/v2.27.1) as of now. Perhaps updating Requests would solve this.
